### ISSUE TITLE
trying to get it to worl

### ISSUE THREAD

**Issue by eldadh** [gutschke/fido-u2f-nginx-lua#1]
Hey
for some reason i cant get it to work, 
i am reciveing this error via console log:

getChallenge(false) /:230:11
handleReply(500, "<html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.7.9</center>
</body>
</html>
") /:98:15
requestFailed()

thnx in advance 
eldadh

**Comment by gutschke** [comment]
Thank you for having done the first step in trying to debug the problem. Yes, looking at the Javascript console is helpful. But in this particular case, all it tells you is that the web server reported an error.

Unfortunately, like many HTTP servers, NGINX doesn't provide much in the way of diagnostic output. You should enable debug support and look into the NGINX error.log file. Hopefully, it'll provide some hints as to what is going wrong. If it doesn't, then you'll have to sprinkle ngx.log() statements throughout the code.

There are just so many different things that can go wrong with deploying code to NGINX, I can't really give more advice. And debugging NGINX configurations can be a little tricky at times. Depends a lot on just what the problem turns out to be (e.g. incorrect file names, incorrect file permissions, syntax errors, ...).
